### ISSUE TITLE
Add Workflow documentation

### ISSUE THREAD

**Issue by Todor-Shishmanov** [Todor-Shishmanov/Genesis#23]
**Describe what the feature will be:**

As the cosmos begins to cool itself and the workflow doesn't undergo rapid (and radical) change every 5 minutes, we can make create documentation - probably in the Nuclino.

Add all basic git workflows
- [x] How are reviews done
- [x] What is test-driven development (TDD) and how do we do it?
- [x] How do we branch each request (first we create a branch for unit tests... e.q.)
- [x] When do we eat/sleep/fight/argue/agree.

**Tasks:**
- [x] [Docs](https://app.nuclino.com/TM-Game/Game-Docs/-Workflow-3fa30e2c-3410-4647-8924-22773a52e54c)

**Comment by Todor-Shishmanov** [comment]
@mirela-manoleva the docs can be found in the Nuclino.

**Comment by mirela-manoleva** [comment]
Approved, moving to "Done". :)
